# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "CheckoutApp"
client_id = "89fa54f5f8af4f57289cd28e8ee3a09f"
application_url = "https://checkout-new--development.gadget.app/api/shopify/install-or-render"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://checkout-new--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "checkoutnew.myshopify.com"
